version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mc:
    image: minio/mc
    container_name: mc
    depends_on: [minio]
    entrypoint:
      - /bin/sh
      - "-c"
      - |
        until mc config host add local http://minio:9000 minioadmin minioadmin; do sleep 1; done
        mc mb local/warehouse
        mc policy set public local/warehouse
        tail -f /dev/null

  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    environment:
      QUARKUS_HTTP_PORT: 19120
    ports:
      - "19120:19120"
      

  spark:
    build: ./spark
    container_name: spark
    depends_on: [minio, nessie]
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_S3_ENDPOINT: http://minio:9000
      NESSIE_URI: http://nessie:19120/api/v2
      WAREHOUSE: /warehouse
    volumes:
      - ./spark/conf:/home/spark/notebooks
      - ./spark/jobs:/opt/spark_jobs:rw
    working_dir: /home/spark/notebooks
    command: >
      bash -c "pip install notebook &&
               jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    #image: apache/airflow:2.7.0
    container_name: airflow
    depends_on: [spark, minio, postgres]
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=wpkcTm8qVuIjMKZpsvUM_wm1EB_hzgRZb7v1wQCeuCI=  # Replace with your secure key
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_S3_ENDPOINT=http://minio:9000
      - NESSIE_URI=http://nessie:19120/api/v2
      - WAREHOUSE=warehouse
    volumes:
      #- ./airflow:/opt/airflow
      #- ./airflow/dags:/opt/airflow/dags
      #- ./spark/jobs:/opt/spark_jobs
      - ./airflow/dags:/opt/airflow/dags
      - ./spark/jobs:/opt/spark_jobs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db init &&
        airflow db migrate &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
        airflow webserver & airflow scheduler"

volumes:
  postgres_data:
  minio_data:
